<?php

declare(strict_types=1);

use Illuminate\Database\Schema\Blueprint;
use Modules\Lang\Models\Post;
use Modules\Xot\Database\Migrations\XotBaseMigration;

return new class extends XotBaseMigration
{
    protected ?string $model_class = Post::class;

    public function up(): void
    {
        // -- CREATE --
        $this->tableCreate(function (Blueprint $table): void {
            $table->string('id')->primary();
            $table->unsignedBigInteger('user_id')->nullable()->index();
            $table->unsignedBigInteger('post_id')->nullable()->index();
            $table->string('lang')->nullable()->index();
            $table->string('guid')->nullable()->unique();
            $table->string('title')->nullable();
            $table->string('subtitle')->nullable();
            $table->string('post_type')->nullable()->index();
            $table->text('txt')->nullable();
            $table->text('content')->nullable(); // Alias for txt or separate field
            $table->text('excerpt')->nullable();
            $table->string('slug')->nullable()->index(); // Generated by HasSlug trait
            $table->string('status')->nullable()->index(); // draft, published, archived, review, scheduled
            $table->dateTime('published_at')->nullable();
            $table->string('locale')->nullable()->index(); // Alias for lang
            $table->string('category')->nullable()->index();
            // ------ IMAGE ---------
            $table->string('image_src')->nullable();
            $table->string('image_alt')->nullable();
            $table->string('image_title')->nullable();
            // ------ SEO FIELDS -----
            $table->string('meta_title')->nullable();
            $table->text('meta_description')->nullable();
            $table->text('meta_keywords')->nullable();
            $table->unsignedBigInteger('author_id')->nullable();
            // ------ BUFFER ----
            $table->string('url')->nullable();
            $table->json('url_lang')->nullable();
            $table->string('image_resize_src')->nullable();
        });

        // -- UPDATE --
        $this->tableUpdate(function (Blueprint $table): void {
            $this->updateTimestamps($table, false);
        });
    }
};
